version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    networks:
      - app-network
    ports:
      - $DB_PORT:3306
    volumes:
      - ./data/db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    command: sh -c "yarn migration:run && yarn start:prod"
    restart: unless-stopped
    env_file: ./.env
    networks:
      - app-network
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true

volumes:
  data:

networks:
  app-network:
    driver: bridge
